import type { Metadata } from "next";
import { Oswald, Inter } from 'next/font/google';
import "./global.css"


const oswald = Oswald({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-heading',
});

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-body',
});

export const metadata: Metadata = {
  title: "IronCore-Fitness",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className=
        {`min-h-full flex flex-col ${oswald.variable} ${inter.variable}`}
      >
        <h1 className={inter.className}>
        </h1>
        {children}
      </body>
    </html>
  );
}
